# Exploratory Data Analysis & Treatment Strategies

## DEMAB : LTN and NTN-F

In [8]:
import pandas as pd
path_demab_refined = r"C:\Users\Dell\OneDrive\Documentos\GitHub\ML-ETTJ26\data\03_refined\bcb\demab\demab_government_bonds_secondary_market_refined.parquet"
demab_refined = pd.read_parquet(path_demab_refined)
demab_refined.info()

<class 'pandas.DataFrame'>
RangeIndex: 197738 entries, 0 to 197737
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   date              197738 non-null  datetime64[us]
 1   isin              197738 non-null  str
 2   sigla             197738 non-null  str
 3   pu_lastro         197738 non-null  float64
 4   valor_par         197522 non-null  float64
 5   issue_date        197738 non-null  datetime64[us]
 6   maturity          197738 non-null  datetime64[us]
 7   days_to_maturity  197738 non-null  int64
 8   bd_to_maturity    197738 non-null  int64
 9   pu_min            187169 non-null  float64
 10  pu_med            187169 non-null  float64
 11  pu_max            187169 non-null  float64
 12  taxa_min          102480 non-null  float64
 13  taxa_med          102480 non-null  float64
 14  taxa_max          102478 non-null  float64
 15  source            197738 non-null  str
 16  raw_hash          197738 non-null  str
dtypes: datetime64[us](3), float64(8), int64(2), str(4)
memory usage: 42.4 MB

In [9]:
df_ltn = demab_refined[demab_refined["sigla"]=="LTN"]
df_ntnf = demab_refined[demab_refined["sigla"]=="NTN-F"]

value_columns = ["date", "isin", "pu_med", "taxa_med", "pu_min", "pu_max", "taxa_min", "taxa_max"]
df_ltn_pu_null = df_ltn[df_ltn["pu_med"].isna()][value_columns]
df_ntnf_pu_null = df_ntnf[df_ntnf["pu_med"].isna()][value_columns]
print(df_ltn_pu_null.info())
print(df_ntnf_pu_null.info())

<class 'pandas.DataFrame'>
Index: 2699 entries, 71 to 196499
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      2699 non-null   datetime64[us]
 1   isin      2699 non-null   str
 2   pu_med    0 non-null      float64
 3   taxa_med  0 non-null      float64
 4   pu_min    0 non-null      float64
 5   pu_max    0 non-null      float64
 6   taxa_min  0 non-null      float64
 7   taxa_max  0 non-null      float64
dtypes: datetime64[us](1), float64(6), str(1)
memory usage: 221.7 KB
None
<class 'pandas.DataFrame'>
Index: 1095 entries, 24 to 162169
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      1095 non-null   datetime64[us]
 1   isin      1095 non-null   str
 2   pu_med    0 non-null      float64
 3   taxa_med  0 non-null      float64
 4   pu_min    0 non-null      float64
 5   pu_max    0 non-null      float64
 6   taxa_min  0 non-null      float64
 7   taxa_max  0 non-null      float64
dtypes: datetime64[us](1), float64(6), str(1)
memory usage: 90.0 KB
None

In [20]:
print(f"Quantidade de ISINs com PU_MED nulo - LTN: {len(df_ltn_pu_null['isin'].unique())}")
print(f"Quantidade de ISINs com PU_MED nulo - NTN-F: {len(df_ntnf_pu_null['isin'].unique())}")

Quantidade de ISINs com PU_MED nulo - LTN: 82
Quantidade de ISINs com PU_MED nulo - NTN-F: 17

In [15]:
df_ntnf[df_ntnf["pu_med"].isna()].info()

<class 'pandas.DataFrame'>
Index: 1095 entries, 24 to 162169
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              1095 non-null   datetime64[us]
 1   isin              1095 non-null   str
 2   sigla             1095 non-null   str
 3   pu_lastro         1095 non-null   float64
 4   valor_par         1095 non-null   float64
 5   issue_date        1095 non-null   datetime64[us]
 6   maturity          1095 non-null   datetime64[us]
 7   days_to_maturity  1095 non-null   int64
 8   bd_to_maturity    1095 non-null   int64
 9   pu_min            0 non-null      float64
 10  pu_med            0 non-null      float64
 11  pu_max            0 non-null      float64
 12  taxa_min          0 non-null      float64
 13  taxa_med          0 non-null      float64
 14  taxa_max          0 non-null      float64
 15  source            1095 non-null   str
 16  raw_hash          1095 non-null   str
dtypes: datetime64[us](3), float64(8), int64(2), str(4)
memory usage: 250.8 KB

In [4]:
df_ltn.head()

,date,isin,sigla,pu_lastro,valor_par,issue_date,maturity,days_to_maturity,bd_to_maturity,pu_min,pu_med,pu_max,taxa_min,taxa_med,taxa_max,source,raw_hash
3,2007-01-02,BRSTNCLTN616,LTN,970.434579,1000.0,2005-09-28,2007-04-01,89,61,970.610716,970.717343,970.746275,12.83,12.84,12.89,BCB_DEMAB,c357e07c5d7074675e559fbbd1dce2fb9fc05c1c869939...
5,2007-01-02,BRSTNCLTN5Z0,LTN,942.652166,1000.0,2005-06-01,2007-07-01,180,123,943.072252,943.260185,944.351897,12.34,12.60,12.65,BCB_DEMAB,c357e07c5d7074675e559fbbd1dce2fb9fc05c1c869939...
7,2007-01-02,BRSTNCLTN632,LTN,914.961886,1000.0,2006-02-13,2007-10-01,272,188,915.940780,916.025352,916.305420,12.43,12.48,12.49,BCB_DEMAB,c357e07c5d7074675e559fbbd1dce2fb9fc05c1c869939...
9,2007-01-02,BRSTNCLTN608,LTN,889.006040,1000.0,2005-07-22,2008-01-01,364,249,882.869221,890.316632,892.080224,12.20,12.42,13.38,BCB_DEMAB,c357e07c5d7074675e559fbbd1dce2fb9fc05c1c869939...
11,2007-01-02,BRSTNCLTN657,LTN,863.854887,1000.0,2006-08-04,2008-04-01,455,311,865.471089,865.471089,865.471089,12.42,12.42,12.42,BCB_DEMAB,c357e07c5d7074675e559fbbd1dce2fb9fc05c1c869939...

### Engine

In [6]:
df_failures = pd.read_parquet(r"C:\Users\Dell\OneDrive\Documentos\GitHub\ML-ETTJ26\data\04_feature\curve_factory\public_bonds\mart_public_bonds_curve_calculation_failures.parquet")
df_failures

,ref_date,instrument_type,isin,issue_date,maturity_date,bd_to_maturity,pu_med,taxa_med,quote_quality,quote_source,primary_quote_type,calculation_status,calculation_error_type,calculation_error_message
0,2010-12-20,NTN-F,BRSTNCNTF0L9,2007-07-06,2011-01-01,8,48.612300,NaN,OBSERVED_PU,PU_MED,PRICE,FAILED,RuntimeError,All yield solvers failed. NewtonYieldSolver: N...
1,2010-12-20,NTN-F,BRSTNCNTF0P0,2010-12-15,2011-07-01,133,46.087200,NaN,OBSERVED_PU,PU_MED,PRICE,FAILED,RuntimeError,All yield solvers failed. NewtonYieldSolver: N...
2,2012-12-24,NTN-F,BRSTNCNTF0T2,2011-12-19,2013-01-01,5,48.742107,NaN,OBSERVED_PU,PU_MED,PRICE,FAILED,RuntimeError,All yield solvers failed. NewtonYieldSolver: N...

In [11]:
df_ntnf[df_ntnf["isin"].isin(df_failures["isin"])]

,date,isin,sigla,pu_lastro,valor_par,issue_date,maturity,days_to_maturity,bd_to_maturity,pu_min,pu_med,pu_max,taxa_min,taxa_med,taxa_max,source,raw_hash
36222,2010-12-20,BRSTNCNTF0L9,NTN-F,48.609050,NaN,2007-07-06,2011-01-01,12,8,48.612300,48.612300,48.612300,NaN,NaN,NaN,BCB_DEMAB,e4b15387e92098e54de1cb5575f4ec5150f772f47bdeb4...
36228,2010-12-20,BRSTNCNTF0P0,NTN-F,46.011226,NaN,2010-12-15,2011-07-01,193,133,46.087200,46.087200,46.087200,NaN,NaN,NaN,BCB_DEMAB,e4b15387e92098e54de1cb5575f4ec5150f772f47bdeb4...
56394,2012-12-24,BRSTNCNTF0T2,NTN-F,48.738503,NaN,2011-12-19,2013-01-01,8,5,48.742107,48.742107,48.742107,NaN,NaN,NaN,BCB_DEMAB,951afba6c0dcfd3beab499d41d6557efc34d9c75616fd5...

In [12]:
df_ntnf.info()

<class 'pandas.DataFrame'>
Index: 26900 entries, 21 to 197727
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              26900 non-null  datetime64[us]
 1   isin              26900 non-null  str
 2   sigla             26900 non-null  str
 3   pu_lastro         26900 non-null  float64
 4   valor_par         26897 non-null  float64
 5   issue_date        26900 non-null  datetime64[us]
 6   maturity          26900 non-null  datetime64[us]
 7   days_to_maturity  26900 non-null  int64
 8   bd_to_maturity    26900 non-null  int64
 9   pu_min            25805 non-null  float64
 10  pu_med            25805 non-null  float64
 11  pu_max            25805 non-null  float64
 12  taxa_min          0 non-null      float64
 13  taxa_med          0 non-null      float64
 14  taxa_max          0 non-null      float64
 15  source            26900 non-null  str
 16  raw_hash          26900 non-null  str
dtypes: datetime64[us](3), float64(8), int64(2), str(4)
memory usage: 6.0 MB